### ISSUE TITLE
Kubevirt Verify Credentials Fails

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-kubevirt#237]
```
[----] E, [2024-07-22T12:26:02.210481#540807:9c68] ERROR -- evm: MIQ(MiqQueue#deliver) Message id: [13488], Error: [wrong number of arguments (given 3, expected 1..2)]
[----] E, [2024-07-22T12:26:02.210775#540807:9c68] ERROR -- evm: [ArgumentError]: wrong number of arguments (given 3, expected 1..2)  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2024-07-22T12:26:02.210935#540807:9c68] ERROR -- evm: /home/grare/adam/.gem/ruby/3.1.0/gems/kubeclient-4.12.0/lib/kubeclient.rb:22:in `initialize'
/home/grare/adam/src/manageiq/fog-kubevirt/lib/fog/kubevirt/compute/compute.rb:371:in `new'
/home/grare/adam/src/manageiq/fog-kubevirt/lib/fog/kubevirt/compute/compute.rb:371:in `create_client_from_token'
/home/grare/adam/src/manageiq/fog-kubevirt/lib/fog/kubevirt/compute/compute.rb:350:in `create_client'
/home/grare/adam/src/manageiq/fog-kubevirt/lib/fog/kubevirt/compute/compute.rb:444:in `kube_client'
/home/grare/adam/src/manageiq/fog-kubevirt/lib/fog/kubevirt/compute/compute.rb:194:in `valid?'
/home/grare/adam/src/manageiq/manageiq-providers-kubevirt/app/models/manageiq/providers/kubevirt/infra_manager/connection.rb:42:in `valid?'
/home/grare/adam/src/manageiq/manageiq-providers-kubevirt/app/models/manageiq/providers/kubevirt/infra_manager.rb:97:in `verify_credentials'
/home/grare/adam/src/manageiq/manageiq-providers-kubernetes/app/models/manageiq/providers/kubernetes/container_manager.rb:692:in `verify_kubevirt_credentials'
/home/grare/adam/src/manageiq/manageiq-providers-kubernetes/app/models/manageiq/providers/kubernetes/container_manager.rb:570:in `block in verify_credentials'
/home/grare/adam/src/manageiq/manageiq-providers-kubernetes/app/models/manageiq/providers/kubernetes/container_manager.rb:586:in `connection_rescue_block'
/home/grare/adam/src/manageiq/manageiq-providers-kubernetes/app/models/manageiq/providers/kubernetes/container_manager.rb:565:in `verify_credentials'
/home/grare/adam/src/manageiq/manageiq/app/models/mixins/verify_credentials_mixin.rb:28:in `verify_credentials?'
```

![image](https://github.com/user-attachments/assets/8b0e50a4-f363-4052-af9f-4430c5e289e3)

**Comment by agrare** [comment]
https://github.com/fog/fog-kubevirt/pull/156
